module.exports = class AdsDetailsEntity {
    
    originalHTML= ""
    hugeJson= ""
    startDate= ""
    endDate= ""
    impressionsText= ""
    reachEstimate= ""
    spend= ""
    currency= ""
    caption= ""
    title= ""
    __html= ""
    publisherPlatform= ""
    cta_text= ""
    cta_type= ""
    extra_images= ""
    extra_links= ""
    link_description= ""
    extra_videos= ""
    display_format= ""
    link_url= ""
    video_hd_url= ""
    video_sd_url= ""
    creation_time= ""
    
}